# Site Settings
title: Chinkhuselts | Cybersecurity Analyst
email: huselee1000@gmail.com
description: >
  Cybersecurity portfolio featuring Network Defense, Snort NIDS, Malware Analysis (CAPEv2), and SIEM integration projects.
baseurl: ""
url: "https://chinkhuselts.github.io"

# Theme Setting
theme: jekyll-theme-hacker

# Plugins
# 'jekyll-seo-tag' makes your site look good when shared on LinkedIn/Discord
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Code Highlighting Settings
# This ensures your Snort rules and Python scripts have color (syntax highlighting)
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Theme Extras
# This adds a "Download as .zip" button to the header (looks cool/technical)
show_downloads: true

# Author Metadata (Used by the SEO plugin)
author:
  name: Chinkhusel Tsolmonbaatar
  github: Chinkhuselts
  linkedin: chinkhusel-tsolmonbaatar-905880271
